In [16]:
## Test the interface to extended_kac
%load_ext autoreload
%autoreload 2
%load_ext line_profiler
from algebra import semisimple_lie_algebra, representations, tensor_product, embedding, test

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
The line_profiler extension is already loaded. To reload it, use:
  %reload_ext line_profiler


In [ ]:
test.run_unit_test(message_detail=True)

In [67]:
algebra = semisimple_lie_algebra.build('E', 8)
#algebra = semisimple_lie_algebra.D(3)

In [25]:
semisimple_lie_algebra.get_valid_algebras()

{'A': algebra.semisimple_lie_algebra.A,
 'B': algebra.semisimple_lie_algebra.B,
 'C': algebra.semisimple_lie_algebra.C,
 'D': algebra.semisimple_lie_algebra.D,
 'E': algebra.semisimple_lie_algebra.E,
 'F': algebra.semisimple_lie_algebra.F,
 'G': algebra.semisimple_lie_algebra.G}

In [68]:
algebra.name

'E(8)'

In [79]:
embedding.regular_embeddings(algebra)

[[ 2 -1  0  0  0  0  0  0 -1]
 [-1  2 -1  0  0  0  0  0  0]
 [ 0 -1  2 -1  0  0  0  0  0]
 [ 0  0 -1  2 -1  0  0  0  0]
 [ 0  0  0 -1  2 -1  0 -1  0]
 [ 0  0  0  0 -1  2 -1  0  0]
 [ 0  0  0  0  0 -1  2  0  0]
 [ 0  0  0  0 -1  0  0  2  0]
 [-1  0  0  0  0  0  0  0  2]]
[2 3 4 5 6 4 2 3]
[[ 2 -1  0  0  0  0  0  0]
 [-1  2 -1  0  0  0  0  0]
 [ 0 -1  2 -1  0  0  0  0]
 [ 0  0 -1  2 -1  0 -1  0]
 [ 0  0  0 -1  2 -1  0  0]
 [ 0  0  0  0 -1  2  0  0]
 [ 0  0  0 -1  0  0  2  0]
 [ 0  0  0  0  0  0  0  2]]
[[ 2 -1  0  0  0  0  0]
 [-1  2 -1  0  0  0  0]
 [ 0 -1  2 -1  0  0  0]
 [ 0  0 -1  2 -1  0 -1]
 [ 0  0  0 -1  2 -1  0]
 [ 0  0  0  0 -1  2  0]
 [ 0  0  0 -1  0  0  2]]
[[0 1 0 0 0 0 0]
 [1 0 1 0 0 0 0]
 [0 1 0 1 0 0 0]
 [0 0 1 0 1 0 1]
 [0 0 0 1 0 1 0]
 [0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0]]
[ 1.  1.  1.  1.  1.  1.]
[[ 2 -1  0  0  0  0  0]
 [-1  2 -1  0  0  0  0]
 [ 0 -1  2 -1  0  0  0]
 [ 0  0 -1  2 -1  0 -1]
 [ 0  0  0 -1  2 -1  0]
 [ 0  0  0  0 -1  2  0]
 [ 0  0  0 -1  0  0  2]]
[[0]]
[]
[

AttributeError: 'NoneType' object has no attribute 'name'

In [ ]:
algebra.cartan_matrix

In [ ]:
algebra.highest_root

In [ ]:
algebra.quadratic_form_matrix

In [ ]:
algebra.rank

In [ ]:
algebra.dual_coxeter_number

In [ ]:
from algebra import roots
sum(roots.comarks(algebra.highest_root, algebra.cartan_matrix, algebra.quadratic_form_matrix)) + 1

In [ ]:
algebra.weyl_order

In [ ]:
algebra.weyl_group

In [ ]:
print(algebra.dynkin_diagram)

In [ ]:
algebra.root_system

In [ ]:
highest_weight_state = [0, 0, 1]#[0, 1, 0]
rep = representations.Irrep(algebra, highest_weight_state)

In [ ]:
from algebra import weyl_group
%lprun -f weyl_group._weyl_reflection rep.weight_lattice

In [ ]:
rep.weight_lattice

In [ ]:
sum([mul for root, mul in rep.weight_lattice])

In [ ]:
rep.dimension

In [ ]:
rep.dynkin_index

In [ ]:
rep.character([1, 1, 1])

In [ ]:
algebra1 = semisimple_lie_algebra.A(3)
rep1 = representations.Irrep(algebra1, [1, 2, 4])
rep2 = representations.Irrep(algebra1, [1, 7, 13])

In [ ]:
print(rep1.dimension)
print(rep2.dimension)

In [ ]:
tensor_product.compute_decomposition(rep1, rep2, as_irreps=True)

In [42]:
chr(10753)

'⨁'

In [ ]:
import lie_algebra.cartan
import lie_algebra.roots
import numpy as np
imp.reload(lie_algebra.cartan)
ect = lie_algebra.cartan.extend_matrix(-algebra.highest_root, algebra.cartan_matrix, algebra.quadratic_form_matrix)
lie_algebra.roots.marks(algebra.highest_root, algebra.cartan_matrix)
#np.dot(lie_algebra.roots.comarks(algebra.highest_root, algebra.cartan_matrix, algebra.quadratic_form_matrix), algebra.highest_root)